name: Deploy Remotely
on:
  push:
    branches: [ main ]
 
jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Transfer Build Folder on EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "."  # Transfer everything in the current directory
        TARGET: ${{ secrets.DEPLOY_TARGET }}

    - name: Restart PM2 Service on EC2 Instance
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem  # Create a temporary key file
        chmod 400 deploy_key.pem                           # Set permissions for the key file
        ssh -o StrictHostKeyChecking=no -i "deploy_key.pem" -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "pm2 restart next-app"
        rm deploy_key.pem                                   # Clean up the key file after use
