name: Deploy Remotely
on:
  push:
    branches: [ main ]

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - run: npm install

    - run: CI=false npm run build

    - name: List files in the working directory
      run: ls -R

    - name: Transfer Necessary Files to EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: ".next public next.config.js package.json package-lock.json"
        TARGET: ${{ secrets.DEPLOY_TARGET }}

    - name: Debug SSH Connection
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 400 deploy_key.pem
        ssh -v -o StrictHostKeyChecking=no -i "deploy_key.pem" -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo Connection Successful"
        rm deploy_key.pem

    - name: Restart PM2 Service on EC2 Instance
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 400 deploy_key.pem
        ssh -o StrictHostKeyChecking=no -i "deploy_key.pem" -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "pm2 restart next-app"
        rm deploy_key.pem
