name: Deploy Remotely

on:
  push:
    branches: [ main ]

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    # Install dependencies and build the project
    - run: npm install
    - run: CI=false npm run build

    # Transfer the necessary files to the EC2 instance
    - name: Transfer Build Folder and Files to EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        # Transfer the .next folder and other essential files like package.json and .env (if required)
        SOURCE: |
          .next/
          package.json
        TARGET: ${{ secrets.DEPLOY_TARGET }}

    # Install dependencies on the EC2 instance and restart the app
    - name: SSH into EC2 and Install Dependencies & Restart App
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.DEPLOY_KEY }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /home/ubuntu/${{ secrets.DEPLOY_TARGET }}
          npm install
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
        EOF
